### ISSUE TITLE
Which implementation get_filtered_documents()

### ISSUE THREAD

**Issue by petelind** [petelind/Mercury#27]
Andrey's (Functional)
Yauhens (Objects)

**Comment by AndreiStepanov1TR** [comment]
Functional

**Comment by petelind** [comment]
Functional

**Comment by TitenkovEA** [comment]
Objects)

**Comment by petelind** [comment]
> Objects)

First one! :)

**Comment by 1psb** [comment]
Objects)

**Comment by petelind** [comment]
Ok, seems like objects win. @astepanovv, sorry about that.
Personally I like functional implementation more, but _vox populi vox dei_.
