### ISSUE TITLE
@OlgaKaz ,  iex() - there is conflict to be resolved.

### ISSUE THREAD

**Issue by petelind** [petelind/Mercury#40]
@OlgaKaz , as agreed - there is conflict to be resolved.
Please take into account that @dmitrypintusov is now supplying you with the list of datapoint blocks to use, and we can assume they are valid.

_Originally posted by @petelind in https://github.com/petelind/Mercury/pull/39#issuecomment-614373308_

**Comment by OlgaKaz** [comment]
Conflicts are resolved
