### ISSUE TITLE
Deploy last version of Lambda to the PROD

### ISSUE THREAD

**Issue by petelind** [petelind/Mercury#71]
Can you please deploy the latest version of lambda (with a fix from @astepanovv) to the AWS, using test data from IEX, and Dynamo table as a persistence? So we can officially close "monitored lambda" milestone?

**Comment by BoykoR** [comment]
I missed a few recent sessions and I wasn't really sure what is considered "PROD". So I updated 'mercury-retriever' lambda that we previously used.
Hopefully that is what I was expected to do.

**Comment by BoykoR** [comment]
The latest version is deployed

**Comment by petelind** [comment]
thx!
