### ISSUE TITLE
CICD: SOURCE stage - pickup the source code from the GitHub

### ISSUE THREAD

**Issue by petelind** [petelind/Mercury#74]
This part of the pipeline does the following:
1. Pickups the source code.
2. Packages it into the SourceArtifact
Add the code to the pipeline definition, to the pipeline.yaml.

**Comment by petelind** [comment]
hi folks, any progress on this one?

**Comment by TitenkovEA** [comment]
> hi folks, any progress on this one?

Hi! I have created PR for this. Also I added secret key for the mercury repo to aws secret manager, but I not sure about correct use it in configuration) Please, take a look on it

**Comment by petelind** [comment]
Good, thank you!
