### ISSUE TITLE
CICD: BUILD stage - prepare the deployment package for the CloudFormation

### ISSUE THREAD

**Issue by petelind** [petelind/Mercury#75]
Use CodeBuild to:
1. Pick up the SourceArtifact.
2. Get buildspec out of it.
3. Package the app for the deployment.
4. Produce BuildArtifact.

Add your code to the pipeline.yaml.

**Comment by petelind** [comment]
hi folks, any progress on this one?

**Comment by petelind** [comment]
Good, thank you!

**Comment by petelind** [comment]
iForgot, sorry.

**Comment by petelind** [comment]
@OlgaKaz , @astepanovv gonna integrate his code with the Parameters section added. Please double-check that parameter names are unified across all sections of code, OK? (He will do also, but 2 pairs of eyes are better than 1).

**Comment by petelind** [comment]
@OlgaKaz , @BoykoR, any progress on that?
If you stuck/vac/cant proceed - let us know, I'll pick up and fix.

**Comment by BoykoR** [comment]
I updated pipeline configuration - added some missing properties. 
pipeline.yaml can now be used to deploy pipeline via CloudFormation.

**Comment by petelind** [comment]
@BoykoR, @OlgaKaz , any updates on the stage?
