### ISSUE TITLE
CICD: TEST Stage - run all the tests we have, fail the build if any of them fails

### ISSUE THREAD

**Issue by petelind** [petelind/Mercury#76]
Run all the tests except the acceptance we have for the app before packaging the app for the deployment.
If one of them fails - fail the build.
(Hint: you'll need a separate build file for that).

Add your code to the pipeline.yaml.

**Comment by petelind** [comment]
hi folks, any progress on this one?

**Comment by petelind** [comment]
Remaining:
1. Integrate even what you have now - sync parameter names across the pipeline.
2. Add "build" stage with its own testspec.yaml which will call CF to deploy stack, run tests, destroy stack.

**Comment by petelind** [comment]
Gents, any progress?

**Comment by YugineS** [comment]
> Gents, any progress?

I'm on vac this week. So didn't do any progress since Friday.
