### ISSUE TITLE
CICD: Create an IAM role containing all the necessary permissions for all other services to use

### ISSUE THREAD

**Issue by petelind** [petelind/Mercury#78]
Think all the services they'll need, try to avoid giving *FullAccess - for most of the cases Read will do.
Put role definition into the pipeline.yaml for all other services to use.

**Comment by gparun** [comment]
Denis, it will be a lot easier for me to write the whole pipeline than just the roles.  I know others team members have been assigned those pipeline steps. They are all inter-connected

**Comment by petelind** [comment]
Yes, plz do roles.
